"""Provider-agnostic interfaces for TTS, streaming TTS, catalogs, and STT."""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from typing import Protocol

from app.voice_profile import audio_media_type


class VoiceProviderError(RuntimeError):
    """Stable error returned when a voice provider cannot fulfill a request."""


class VoiceProviderCredentialError(VoiceProviderError):
    """Raised when provider credentials are missing or incomplete."""


@dataclass(frozen=True, slots=True)
class VoiceProviderInfo:
    """Public metadata for one configured or potential voice provider."""

    id: str
    display_name: str
    configured: bool
    supports_tts: bool = True
    supports_streaming: bool = False
    supports_telephony_codec: bool = False
    supports_stt: bool = False
    supports_voice_clone: bool = False
    requires_consent: bool = False
    recommended: bool = False
    enabled: bool = True
    notes: str | None = None


@dataclass(frozen=True, slots=True)
class VoiceCatalogItem:
    """One safe, selectable voice/model option."""

    provider: str
    model: str
    voice_id: str
    display_name: str
    locale: str | None = None
    language: str | None = None
    gender: str | None = None
    supports_streaming: bool = False
    supports_telephony_codec: bool = False
    supports_voice_clone: bool = False
    requires_consent: bool = False
    recommended: bool = False
    enabled: bool = True


@dataclass(frozen=True, slots=True)
class TTSRequest:
    """Provider-neutral finite TTS request."""

    text: str
    provider: str
    model: str | None
    voice_id: str
    instructions: str | None = None
    response_format: str = "mp3"
    output_audio_format: str = "pcm16"
    telephony_codec: str = "pcmu"
    locale: str | None = None
    gender: str | None = None
    voice_speed: Decimal = Decimal("1.00")
    voice_pitch: Decimal = Decimal("0.00")
    voice_stability: Decimal | None = None
    voice_similarity: Decimal | None = None
    voice_temperature: Decimal | None = None


@dataclass(frozen=True, slots=True)
class TTSResult:
    """Audio generated by one TTS provider."""

    audio: bytes
    media_type: str

    @classmethod
    def from_format(cls, audio: bytes, response_format: str) -> TTSResult:
        """Build a result using the existing preview format media types."""
        return cls(audio=audio, media_type=audio_media_type(response_format))


class TTSProvider(Protocol):
    """Finite text-to-speech provider interface."""

    provider_id: str

    def info(self) -> VoiceProviderInfo:
        """Return safe provider metadata."""

    def synthesize(self, request: TTSRequest) -> TTSResult:
        """Generate one finite audio response and close all resources."""


class StreamingTTSProvider(Protocol):
    """Streaming text-to-speech provider interface for future media bridge use."""

    provider_id: str

    def info(self) -> VoiceProviderInfo:
        """Return safe provider metadata."""

    def supports_streaming_tts(self) -> bool:
        """Return whether this provider can stream generated audio."""


class VoiceCatalogProvider(Protocol):
    """Provider interface for static or remote voice catalog entries."""

    provider_id: str

    def info(self) -> VoiceProviderInfo:
        """Return safe provider metadata."""

    def catalog(self) -> list[VoiceCatalogItem]:
        """Return known voices, optionally fetched from an official API."""


class STTProvider(Protocol):
    """Optional speech-to-text provider interface."""

    provider_id: str

    def info(self) -> VoiceProviderInfo:
        """Return safe provider metadata."""

    def transcribe(self, audio: bytes, *, media_type: str, language: str | None) -> str:
        """Transcribe a finite audio blob."""
